# Site settings
title: Tyler Kent
header-img: img/cap1.jpg
email: tyler.kent@mail.utoronto.ca
description: "Personal site for Tyler Kent"
baseurl: ""
url: "tvkent.github.io"
twitter_username: tylervkent
github_username:  tvkent

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
